# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54a562b948eaea459afbd23e1c5aeb78"
name = "Chargemind"
application_url = "https://app.chargemind.io"
embedded = false

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_shopify_payments_payouts,read_shopify_payments_disputes,write_shopify_payments_disputes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://app.chargemind.io/auth/callback" ]

[app_proxy]
url = "https://xieephvojphtjayjoxbc.supabase.co/functions/v1/app-proxy-render"
subpath = "resolution"
prefix = "apps"